apiVersion: apps/v1
kind: Deployment
metadata:
  name: happy-world-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: happy-world-app
  template:
    metadata:
      labels:
        app: happy-world-app
    spec:
      containers:
        - name: happy-world-app
          image: 656967617759.dkr.ecr.us-east-1.amazonaws.com/eks-lab:happy-world-app-5
          ports:
            - containerPort: 5001