apiVersion: v1
kind: Service
metadata:
  name: happy-world-service
spec:
  selector:
    app: happy-world-app
  ports:
    - protocol: TCP
      port: 81
      targetPort: 5001
  type: NodePort